config/routes.rb
Rails.application.routes.draw do
  root 'diaries#index'
  devise_for :users
  resources :diaries
  resources :users, only: :show
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :diaries
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, except: [:index, :show]

  # GET /diaries
  # GET /diaries.json
  def index
    @diaries = Diary.includes(:user)
  end

  # GET /diaries/1
  # GET /diaries/1.json
  def show
  end

  # GET /diaries/new
  def new
    @diary = Diary.new
  end

  # GET /diaries/1/edit
  def edit
  end

  # POST /diaries
  # POST /diaries.json
  def create
    @diary = Diary.new(diary_params)
    respond_to do |format|
      if @diary.save
        format.html { redirect_to @diary }
        format.json { render :show, status: :created, location: @diary }
      else
        format.html { render :new }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diaries/1
  # PATCH/PUT /diaries/1.json
  def update
    respond_to do |format|
      if @diary.update(diary_params)
        format.html { redirect_to @diary, notice: 'Diary was successfully updated.' }
        format.json { render :show, status: :ok, location: @diary }
      else
        format.html { render :edit }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diaries/1
  # DELETE /diaries/1.json
  def destroy
    @diary.destroy
    respond_to do |format|
      format.html { redirect_to diaries_url, notice: 'Diary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_diary
    @diary = Diary.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def diary_params
    params.require(:diary).permit(:content, :date).merge(user_id: current_user.id)
  end
  
  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @name = user.name
    @diaries = user.diaries
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録ができました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/diaries/_form.html.erb
<%= form_with(model: diary, local: true) do |form| %>
  <% if diary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(diary.errors.count, "error") %> prohibited this diary from being saved:</h2>

      <ul>
        <% diary.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  
<% end %>

app/views/diaries/edit.html.erb
<h2>編集</h2>

<%= render 'form', diary: @diary %>

<%= link_to 'TOPへ戻る', diaries_path %>

app/views/diaries/index.html.erb
<header>
  <% if user_signed_in? %>
    <div class="user_nav grid-6">
      <span><%= current_user.name %>
        <ul class="user__info">
          <%= link_to "マイページ", "/users/#{current_user.id}" %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      </span>
      <%= link_to "投稿する", new_diary_path, class: "post" %>
      <%= link_to 'TOPに戻る', diaries_path %>
    </div>
  <% else %>
    <div class="grid-6">
      <%= link_to "ログイン", new_user_session_path, class: "post" %>
      <%= link_to "新規登録", new_user_registration_path, class: "post" %>
    </div>
  <% end %>
</header>

<main>
  <h1> Enjoy your Life, Feel Happy!</h1>
  <img alt="" src="/assets/positive.jpg" />
</main>

app/views/diaries/new.html.erb
<h2>今日も1日おつかれさま！
  <br/>あなたにとって明日も良い日になりますように。<br>
</h2>

<img alt="SMILE" src="/assets/uyuniko.jpg" />

<h2>1日をふりかえり、よかった事を書き出していこう！</h2>

<%= render 'form', diary: @diary %>
<%= link_to 'TOPに戻る', diaries_path %>

app/views/diaries/show.html.erb
<p>
  <strong>内容:</strong>
  <%= @diary.content %>
</p>

<p>
  <strong>日付:</strong>
  <%= @diary.date %>
</p>


<%= link_to '編集', edit_diary_path(@diary) %> |
<%= link_to '削除', @diary, method: :delete, data: { confirm: '本当に削除しますか？'} %>
<%= link_to '一覧に戻る', diaries_path %>

app/views/layouts/_flash.html.erb
<div class="Flash">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: key %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HAPPY DIARY</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/flash' %>
    <%= yield %>
    <footer>
      <p>
        Copyright HAPPY DIARY 2020.
      </p>
    </footer>
  </body>

</html>

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__title
    %h2 Edit Account
    %h5 アカウントの編集
    = link_to "ログアウト", '#', class: 'Button'
    = link_to "トップページに戻る", :back, class: 'Button'
  .AccountPage__form
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :name
        .FormField__input--normal
          = f.text_field :name, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :email
        .FormField__input--normal
          = f.email_field :email
      = f.submit "Update", class: 'Button UserButton'

app/views/users/show.html.erb
<div class="contents row">
  <p>[投稿一覧]</p>
  <% @diaries.each do |diary| %>
    <div class="Info" >
      <div class="text">
        <p>日付：<%= diary.date %></p>
        <p>内容：<%= diary.content %></p>
      </div>
      <div class="link" style="display:flex">
        <p style="margin:5px"><%= link_to '編集', edit_diary_path(diary) %></p>
        <p style="margin:5px"><%= link_to '削除', diary, method: :delete, data: { confirm: '本当に削除しますか?' } %></p>
      </div>
    </div>
  <% end %>
  <%= link_to 'TOPに戻る', diaries_path %>
</div>